### ISSUE TITLE
[Feature]: Add "More Origins!" addon 

### ISSUE THREAD

**Issue by b0bbin** [TheButterbrotMan/Deathdusk#12] opened 2022-02-06 14:56 UTC
### Is your feature request related to a problem? Please describe.

It is a suggestion

### Describe the solution you'd like

You can add the More Origins! addon to add some mob origins to the modpack.

The More Origins! addon can be found here:
https://www.curseforge.com/minecraft/mc-addons/more-origins

### Additional context

I suggested in the discord adding the More Origns! addon with the orgins mod to add some mob origins to the modpack and you said you would add them but to make a feature request to help your organise it so here I am.

**Comment by TheButterbrotMan** [comment] 2022-02-06 14:57
Thank you.

Duplicate of #6

**Closed by TheButterbrotMan** 2022-02-06 14:57 UTC
