### ISSUE TITLE
[Bug]: Nether generation server crash

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#93] opened 2022-05-29 23:56 UTC
### What happened?

If we generate certain structures the server implodes I think it was a piglin outpost for what wild said.

### Version

2.0.6 AT THE MOMENT OF THE CRASH

**Comment by TheButterbrotMan** [comment] 2022-05-30 15:03
Duplicate of #87

**Closed by TheButterbrotMan** 2022-05-30 15:03 UTC
