### ISSUE TITLE
[Bug]: Issues with origins that utilize commands

### ISSUE THREAD

**Issue by abcdeed7** [TheButterbrotMan/Deathdusk#13] opened 2022-02-07 04:50 UTC
### What happened?

On origins that utilize Pehkui along with some other features, commands are used to change the character's size and to do other things. One issue is the myconid origin fully not functioning. as most of it's features work through this effect. 

### Version

2.9.3

### Provide the log

N/A

**Comment by abcdeed7** [comment] 2022-02-07 15:51
its not that specific commands aren't working, its that when an origin is assigned it does commands (so specifically for example, when you choose the ogre origin (from medieval origins) it runs commands to set your scale, (part of the gargantuan power, in [gargantuan.json](https://github.com/Deadbones2000/Medieval-Origins/blob/e3cdae0f6cffcfd93c5dd8c25f19f854aad6fc6a/src/main/resources/data/medievalorigins/powers/gargantuan.json)) 
this calls on some functions, notably [ogre_callback.mcfunction](https://github.com/Deadbones2000/Medieval-Origins/blob/e3cdae0f6cffcfd93c5dd8c25f19f854aad6fc6a/src/main/resources/data/medievalorigins/functions/mdvlorigins/ogre_callback.mcfunction) and runs the commands 

> scale reset pehkui:base
> scale persist reset pehkui:base @s

it then runs [ogre_callon.mcfunction](https://github.com/Deadbones2000/Medieval-Origins/blob/e3cdae0f6cffcfd93c5dd8c25f19f854aad6fc6a/src/main/resources/data/medievalorigins/functions/mdvlorigins/ogre_callon.mcfunction) and that sets the scale of your character with the commands 

> scale set pehkui:base 1.55
> scale persist set pehkui:base true @s

None of these commands are working, this breaks all origins that utilize commands; so all of apoc and most of medieval. Something is blocking these commands from running and I'm not sure what

**Comment by TheButterbrotMan** [comment] 2022-02-07 17:10
Player Roles

**Comment by TheButterbrotMan** [comment] 2022-02-07 17:15
Its probably Player Roles, i will try to fix it, but it seems the problem is more deep than i thougth.

**Comment by TheButterbrotMan** [comment] 2022-02-07 21:46
Fixed in 2.9.4

**Closed by TheButterbrotMan** 2022-02-07 21:46 UTC
Labels: bug, help wanted
