### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Keshav-Nagar** [TheButterbrotMan/Deathdusk#27] opened 2022-03-17 05:27 UTC
### What happened?

I created a new singleplayer world and MC stopped responding and a minute later I got a crash report

### Version

1.0.1

### Provide the log

[https://bytebin.lucko.me/CCEA3XbeYD](url)

**Comment by TheButterbrotMan** [comment] 2022-03-17 07:29
Duplicate of #26

**Closed by TheButterbrotMan** 2022-03-17 07:29 UTC
