### ISSUE TITLE
[Bug]: Incompatibility between Immersive Portals and Bits & Chisels

### ISSUE THREAD

**Issue by ZeroTronix** [TheButterbrotMan/Deathdusk#52] opened 2022-05-10 17:02 UTC
### What happened?

When you create a new block with chisel and bits the block is bugged and invisible.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/94763000/167683291-03cd7c2d-7012-4209-9ac4-3cfbfab3184e.png">

### Version

Latest

**Comment by TheButterbrotMan** [comment] 2022-05-10 18:11
Can you reproduce this in singleplayer?

**Comment by ZeroTronix** [comment] 2022-05-10 18:21
Testet it now in Singleplayer it is the same problem

**Comment by ZeroTronix** [comment] 2022-05-10 21:00
Ok i tryed it with the original 2.0 version and had the same problem. Couldend try to remove that with immersive portals(time problems) but here is the log how far i can say the log say nothing https://bytebin.lucko.me/ry20YbIbxU

**Comment by TheButterbrotMan** [comment] 2022-05-12 13:28
I couldnt reproduce it, but https://github.com/qouteall/ImmersivePortalsMod/issues/963

**Comment by TheButterbrotMan** [comment] 2022-05-18 19:52
Fixed in 2.0.3.

**Closed by TheButterbrotMan** 2022-05-18 19:52 UTC
Labels: bug, help wanted, low priority, external problem
